### ISSUE TITLE
Create the system UI and UX designs.

### ISSUE THREAD

**Issue by efonsecab** [efonsecab/FairPlayTube#108]
Currently, the system has a basic UI, mainly focused to show the system functionality, however, the current design is way too basic, and is lacking a good UX (User Experience)..

Also, we are targeting for system to have as much UI as possible to be reusable when implementing the MAUI Blazor version, for mobile devices, so UI designs need to take into consideration that they must be cross-platform compatible and look good on Desktops, and mobile devices.

Create some mockups for: 
* Navigation
* Public Home Page
* Search Videos By Keyword
* Upload Videos
* User Messages

**Comment by calvinmorett** [comment]
Currently creating some concepts.

---------

![image](https://user-images.githubusercontent.com/11654917/127207427-993811d2-ea8d-4074-b0dc-abf80af0e1c9.png)

---------

![tacotaco](https://user-images.githubusercontent.com/11654917/127208097-22860f9d-9d6f-4b35-85b4-910a579fc496.gif)
https://codepen.io/CalvinMorett/full/YzVeeaG

Layout, needs to be refined, current state:
https://codepen.io/CalvinMorett/full/ZEKryoW

**Comment by efonsecab** [comment]
> Currently creating some concepts.
> 
> ![image](https://user-images.githubusercontent.com/11654917/127207427-993811d2-ea8d-4074-b0dc-abf80af0e1c9.png)
> 
> ![tacotaco](https://user-images.githubusercontent.com/11654917/127208097-22860f9d-9d6f-4b35-85b4-910a579fc496.gif)
> https://codepen.io/CalvinMorett/full/YzVeeaG
> 
> Layout, needs to be refined, current state:
> https://codepen.io/CalvinMorett/full/ZEKryoW

That's great, looking forward to see how it ends up.
P.D.: I want tacos! 🤣

**Comment by efonsecab** [comment]
@all-contributors please add @calvinmorett  for design

**Comment by efonsecab** [comment]
@calvinmorett assigned the issue to you just to have better control on which tasks are still without anyone working on them.

**Comment by calvinmorett** [comment]
![Screenshot 2021-07-27 at 23-20-00 CodePen - A Pen by Calvin](https://user-images.githubusercontent.com/11654917/127258410-8606cb0c-7ad2-4b60-9027-9e1d65413992.png)

https://codepen.io/CalvinMorett/full/GRmQPoL

**Comment by efonsecab** [comment]
> ![Screenshot 2021-07-27 at 23-20-00 CodePen - A Pen by Calvin](https://user-images.githubusercontent.com/11654917/127258410-8606cb0c-7ad2-4b60-9027-9e1d65413992.png)
> 
> https://codepen.io/CalvinMorett/full/GRmQPoL
> 
> Using all this food was a bad idea.

Nice, looks great. Would you mind to explain me a bit the purpose of the "X" on the cards header, and the small play section (is that representing the ability to "minimize" the video while playing?)

hahaha, indeed, all that food makes you hungry

**Comment by calvinmorett** [comment]
I wanted to allow the user to control what they were seeing. If there is something they don't want to see, you can click the X to hide it/obscure it.

![close](https://user-images.githubusercontent.com/11654917/127340702-b932fd93-c9d4-4f12-b1be-ca6525d9b530.gif)

--------------

![Screenshot 2021-07-28 at 10-32-43 CodePen - A Pen by Calvin](https://user-images.githubusercontent.com/11654917/127341079-d111dc91-130c-4ed9-8d7c-c490445343ba.png)

**Comment by efonsecab** [comment]
> I wanted to allow the user to control what they were seeing. If there is something they don't want to see, you can click the X to hide it/obscure it. Now that I think of it, perhaps this could be a default setting for NSFW items.
> 
> ![close](https://user-images.githubusercontent.com/11654917/127340702-b932fd93-c9d4-4f12-b1be-ca6525d9b530.gif)
> 
> ![Screenshot 2021-07-28 at 10-32-43 CodePen - A Pen by Calvin](https://user-images.githubusercontent.com/11654917/127341079-d111dc91-130c-4ed9-8d7c-c490445343ba.png)

Looks really good.

**Comment by calvinmorett** [comment]
Can we confirm or define these items a little more? My definitions won't be the same as yours, so want to clarify. 

Examples of breadcrumbs would help as well so I can see some different scenarios of pages. Use the Search example of results found and not found to think about other states of the same page.
```
[ Home > Username > User Messages: User logged in ]
[ Home > Username > User Messages: User not logged in ]
```
```

[ Home > Username > Videos > Users who bought this item ]
[ Home > Username > Videos > Users who liked this item ]
```

```
[ Home > Search > Results: Found ]
[ Home > Search > Results: No items found]
```

-     Navigation: Page links everyone sees regardless of access. Page links specific to a logged in user. 
-     Public Home Page: Not logged in users will see this.
-     Search Videos By Keyword: Not sure if we need to specify keywords. This will be a self contained page, that also shows results.
-     Upload Videos: This is a video upload form page.
-     User Messages: This is comments on videos, or messages from user to user?

**Comment by efonsecab** [comment]
@calvinmorett Hello, I'll try to answer here
One of the system's goal is have users create a community and help each other grow, then we are enforcing account creation on user specific actions.
Items like the Buy Video can be displayed on the public page, but they will first enforce the user to create an account.
On the Home Page, we will go away from the common pattern on video portals, and we what we will show instead is two sections
* New free videos sorted by date of creation and user audience size (smallest first)
* New paid videos sorted by date of creation and user audience size (smallest first)

For the logged in user pages, we may show the ability to do custom sorting

The User Messages is to send messages to another user, logged in users will be able to see a users list:
https://fairplaytube.pticostarica.com/Users/List
that page will eventually have an icon to be able to message a user:
https://github.com/efonsecab/FairPlayTube/issues/217
Later on users will be able to send message from other places of the system
The Search By Keyword currently is just a concept, we want to allow users to have multiple ways of searching:
* Keywords
* Person name (name of persons identified appearing in the videos), something like this: https://fairplaytube.pticostarica.com/Persons

As for the keywords one of the things were were thinking is if it would be good to have something like a tags cloud, but since there can be too many, we are not sure

Please let me know if that answer your questions.
