### ISSUE TITLE
Blank spaces on menu

### ISSUE THREAD

**Issue by efonsecab** [efonsecab/FairPlayTube#143]
**Describe the bug**
When loading an empty page and scrolling down, the layout displays a lot of white space on the nav bar

**To Reproduce**
1. Log in
2. Click the "Videos Queue" icon. The one that looks like a list
3. Scroll down

**Expected behavior**
Navigation menu layout  is consistent among page and navigation

**Screenshots**
![image](https://user-images.githubusercontent.com/3481899/126916379-0d2d537b-36e7-4776-b8cd-95ef7a7ffae6.png)

**Comment by efonsecab** [comment]
@FedericoJoseLucia @FedericoJoseLucia 
Do you have any idea of why this happens?

**Comment by FedericoJoseLucia** [comment]
@efonsecab Yes, I think it may have something to do with using both "sticky" and "vh 100 height" at the same time. Would you like to assign it to me?

**Comment by efonsecab** [comment]
> @efonsecab Yes, I think it may have something to do with using both "sticky" and "vh 100 height" at the same time. Would you like to assign it to me?

Sure.
